In [234]:
#1. use this data to solve subsequent challenges
import numpy as np
data = np.arange(1,26).reshape(5,5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [258]:
# 2. bring out the following from data above array
#array([[12, 13, 14, 15],
#        [17, 18, 19, 20],
#        [22, 23, 24, 25]])

data[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [264]:
# 3. produce the output below from the data above
# array([[ 2],
#        [ 7],
#        [12]])
data[:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [231]:
# 4. produce the output below from the data above
# array([21, 22, 23, 24, 25])
data[4]

array([21, 22, 23, 24, 25])

In [60]:
# 5. Get the sum of all the values in data
total = np.sum(data)
print(total)

325


In [283]:
# # 6. Get the sum of all the columns in data
# import matplotlib.pyplot as plt

data.sum(0)

array([55, 60, 65, 70, 75])

In [282]:
# # 7. Create a function that grabs the email and return then website domain from a string 
# # eg. if you pass in wale@gmail.com, it should return gmail.com
def Gmail(email):
    
    return email.split('@')[-1]

Gmail('fadeyinmi@gmail.com')

'gmail.com'

In [113]:
#Create a function that returns True if a word contain 'tech' in an input string.
# eg. "Welcome to black tech" should return True while "I am learning python" will return False

Greeting = "Welcome to black tech"
greeting_sub = "tech"

if Greeting.find(greeting_sub) != -1:
    print("True")
else:
    print("False")

True


In [101]:
Greeting = "I am learning python"
greeting_sub = "tech"

if Greeting.find(greeting_sub) != -1:
    print("True")
else:
    print("False")

False


In [119]:
# Create a function that count number of times "black" occour in a string
# eg. "black tech is making impact not just for black but globally"
speech = 'black tech is making impact not just for black but globally'
speech.count('black')

2

In [226]:
#10. You are driving fast and was stopped by a police. 
#Create a program that return "no ticket" if your speed is less than or equal 50. 
#It should return "medium" if your speed is above 50. Return "High ticket" if your speed is above 90.


if speed <= 50:
    print ("no ticket")
elif speed > 50 and speed < 90:
    print ("medium")
elif speed >= 90:
    print ("High Ticket")
else:
    print ('None')
    
speed = 50

no ticket
